module.exports = {
  apps: [
    {
      name: "cloud-devops-project",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3000 -H 0.0.0.0",
      watch: false,
      cwd: "/opt/cloud-devops-project",
      exec_mode: "fork",
      instances: 1,
      autorestart: false,
      kill_timeout: 5000,
      listen_timeout: 8000,
      env: {
        NODE_ENV: process.env.NODE_ENV || "production",
        ENVIRONMENT: process.env.ENVIRONMENT || "development",
        CPU: process.env.CPU || "0",
        MEMORY: process.env.MEMORY || "0",
        PROCESS_STATUS: process.env.PROCESS_STATUS || "unknown",
        UPTIME: process.env.UPTIME || "0",
        RESTART_COUNT: process.env.RESTART_COUNT || "0",
      },
      env_development: {
        NODE_ENV: process.env.NODE_ENV || "production",
        ENVIRONMENT: process.env.ENVIRONMENT || "development",
        CPU: process.env.CPU || "0",
        MEMORY: process.env.MEMORY || "0",
        PROCESS_STATUS: process.env.PROCESS_STATUS || "unknown",
        UPTIME: process.env.UPTIME || "0",
        RESTART_COUNT: process.env.RESTART_COUNT || "0",
      },
      env_production: {
        NODE_ENV: process.env.NODE_ENV || "production",
        ENVIRONMENT: process.env.ENVIRONMENT || "production",
        CPU: process.env.CPU || "0",
        MEMORY: process.env.MEMORY || "0",
        PROCESS_STATUS: process.env.PROCESS_STATUS || "unknown",
        UPTIME: process.env.UPTIME || "0",
        RESTART_COUNT: process.env.RESTART_COUNT || "0",
      },
    },
  ],
};
