name: Deploy to EC2

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      ENVIRONMENT: ${{ github.ref_name == 'prod' && 'production' || 'development' }}
      INSTANCE_ID: ${{ github.ref_name == 'prod' && vars.PROD_INSTANCE_ID || vars.DEV_INSTANCE_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Set Build Info
        run: |
          echo "VERSION=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "COMMIT_HASH=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
          echo "DEPLOY_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy
        run: |
          aws ssm send-command \
            --instance-ids $INSTANCE_ID \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy from GitHub Actions" \
            --cloud-watch-output-config CloudWatchOutputEnabled=true \
            --parameters 'commands=[
            "uptime",
            "cd /opt/cloud-devops-project",
            "git config --global --add safe.directory /opt/cloud-devops-project",
            "git fetch origin",
            "git switch ${{ github.ref_name }} || git switch -C ${{ github.ref_name }} origin/${{ github.ref_name }}",
            "git reset --hard origin/${{ github.ref_name }}",
            "cat > .env.${{ github.ref_name }} <<EOF
          NODE_ENV=${ENVIRONMENT}
          ENVIRONMENT=${ENVIRONMENT}
          AWS_REGION='${{ env.AWS_REGION }}'
          VERSION='${VERSION}'
          COMMIT_HASH='${COMMIT_HASH}'
          BRANCH='${BRANCH}'
          BUILD_TIME='${BUILD_TIME}'
          DEPLOY_TIME='${DEPLOY_TIME}'
          EOF",
            "rm -rf .next",
            "npm ci --no-audit --no-fund",
            "npm run build",
            "pm2 restart cloud-devops-project || pm2 start npm --name cloud-devops-project -- start -- -H 0.0.0.0"
            ,]' \
            --region ${{ env.AWS_REGION }}
