name: Deploy to EC2

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd cloud-devops-project
            git reset --hard origin/prod
            npm ci --omit=dev --no-audit --no-fund
            npm run build
            pm2 restart cloud-devops-project || pm2 start npm --name "cloud-devops-project" -- start -- -H 0.0.0.0
          EOF
